### PR TITLE
use config file instead of editing /etc/chilli/defaults

### PR DESCRIPTION
**Pull request by reigelgallarde**
Let's do it coovachilli way... as stated in the file /etc/chilli/defaults:
````
# -*- mode: shell-script; -*-
#
#   Coova-Chilli Default Configurations. 
#   To customize, copy this file to /etc/chilli/config
#   and edit to your liking. This is included in shell scripts
#   that configure chilli and related programs before file 'config'. 
````

also easier to further customized to everyone's need.

### CODE REVIEW

**Comment by reigelgallarde** [comment]
this is also safe when there's a need to reinstall, when coovachilli is being uninstalled, it will leave a copy of your config. The copy is /etc/chilli/config.save.

**Comment by pihomeserver** [comment]
Very good PR ! 
I will update it to take into account HS_MACAUTH and HS_MACPASSWD (there are sed commands but no value in the config file) and add a test in the script to backup the file with a timestamp.

If you want the script to be rerunnable then a lot of conditions should be added like Coova compile, SQL instructions, etc

**Comment by reigelgallarde** [comment]
I updated the sed.. reference: https://superuser.com/a/976712/27501

**Comment by reigelgallarde** [comment]
I don't really need it to be rerunnable... there's just some times when everything is okay but there's a problem with coovachilli... I don't want to rerun the script, I will just reinstall coova... then my config is lost... I have to do it manually too... but now, config.save is there for reference of the old config you have.

**Comment by reigelgallarde** [comment]
This PR is just for convenience though..

**Comment by pihomeserver** [comment]
Currently testing the installation with this script. No issue on the execution but the authentication does not work and fails with an access-reject from freeradius because it sends a User-Password and not a Cleartext-password
```
root@raspberrypi:~# echo User-Name='chris',User-Password='chris' | radclient -c '1' -n '3' -r '3' -t '3' -x '127.0.0.1:1812' 'auth' 'tYUYhUvWfshqS6RXM1NBtk4rCWJt7B0Z'
Sent Access-Request Id 117 from 0.0.0.0:56274 to 127.0.0.1:1812 length 45
	User-Name = "chris"
	User-Password = "chris"
	Cleartext-Password = "chris"
Received Access-Accept Id 117 from 127.0.0.1:1812 to 0.0.0.0:0 length 20
root@raspberrypi:~# echo User-Name='chris',Cleartext-Password='chris' | radclient -c '1' -n '3' -r '3' -t '3' -x '127.0.0.1:1812' 'auth' 'tYUYhUvWfshqS6RXM1NBtk4rCWJt7B0Z'
WARNING: No password in the request
Sent Access-Request Id 221 from 0.0.0.0:33732 to 127.0.0.1:1812 length 27
	User-Name = "chris"
	Cleartext-Password = "chris"
Received Access-Reject Id 221 from 127.0.0.1:1812 to 0.0.0.0:0 length 20
```
Did you get the same error on your side ?

**Comment by reigelgallarde** [comment]
I made changes... 
HS_UAMSECRET should be empty for coovachilli JSON to work.
can you please check?
no need to re run the script if you already have one setup.
just add `HS_UAMSECRET=` to `/etc/chilli/config`

**Comment by pihomeserver** [comment]
Already tested that yesterday but still not working. I will test again later. Maybe i missed something ...

**Comment by pihomeserver** [comment]
A reboot and all works fine ...

**Pull request merged**
