### PR TITLE
Fixed typo errors.. ipt -> iptables

### PR DESCRIPTION
**Pull request by lfasmpao**
_ipt_ should be _iptables_ except you tried to symlink _iptables_ to _ipt_

### CODE REVIEW

**Comment by reigelgallarde** [comment]
if you'll look at /etc/chilli/up.sh, you will see it's ipt

**Comment by reigelgallarde** [comment]
there's actually a function ipt inside up.sh.. and that's what's being called...

**Comment by pihomeserver** [comment]
Correct that's why ipt is used instead of iptables.

**Comment by lfasmpao** [comment]
Well, I just modified my own coovachilli configuration 😓

**Pull request closed without merging**
